sudo: required
services:
  - docker

before_install:
  - docker build -t chaimailankody/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chaimailankody/react-test npm test

after_success:
  - docker build -t chaimailankody/multi-client ./client
  - docker build -t chaimailankody/multi-nginx ./nginx
  - docker build -t chaimailankody/multi-server ./server
  - docker build -t chaimailankody/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push chaimailankody/multi-client
  - docker push chaimailankody/multi-nginx
  - docker push chaimailankody/multi-server
  - docker push chaimailankody/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-262036539745
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY